package com.example.books;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:3000") //Allow CORS from this origin
@RequestMapping(path="/book") // This means URL's start with /book (after Application path)
public class BookController {
  @Autowired // This means to get the bean called BooksRepository
             // Which is auto-generated by Spring, we will use it to handle the data
  private BooksRepository booksRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewBook (@RequestParam String name,
         @RequestParam String author,
         @RequestParam Integer year) {
  // @ResponseBody means the returned String is the response, not a view name
  // @RequestParam means it is a parameter from the GET or POST request

    Book b = new Book();
    b.setName(name);
    b.setAuthor(author);
    b.setYear(year);
    booksRepository.save(b);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Book> getAllBooks() {
    // This returns a JSON or XML with the books
    return booksRepository.findAll();
  }
}