name: build_and_deploy
on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - run: ./mvnw clean install -Dmaven.test.skip=true
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: target/books-0.0.1-SNAPSHOT.jar
        remote_path: /opt/applications/books-be/
        remote_host: 3.237.77.85
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Kill old process and start the new version one
      uses: appleboy/ssh-action@v0.1.8
      env:
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      with:
        host: 3.237.77.85
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          pkill -9 -f java
          nohup java -jar /opt/applications/books-be/books-0.0.1-SNAPSHOT.jar > /opt/applications/books-be/books-be.log 2> /opt/applications/books-be/books-be.error < /dev/null &
          echo "deployment complete"